config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :rooms, except: [:edit, :update] do
    resources :wishlists, only: [:index, :create]
    resources :planners, only: [:index, :create]
  end
  resources :wishlists, only: [:destroy]
  resources :planners, only: [:destroy]
end

app/models/planner.rb
class Planner < ApplicationRecord
  self.table_name = "frnshr_planners"
  belongs_to :room, foreign_key: "frnshr_room_id"
  belongs_to :item, foreign_key: "frnshr_item_id"
end

app/controllers/planners_controller.rb
class PlannersController < ApplicationController
  def index
    @planners = policy_scope(Planner)
    @room = Room.find(params[:room_id])
    @planners = @planners.where(room: @room)
    @wishlists = @room.wishlists
    @planner = Planner.new
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "file_name.pdf", template: "planners/_printing", layout: 'pdf', formats: [:html]
      end
    end
  end

  def create
    @room = Room.find(params[:room_id])
    @planner = Planner.new(planner_params)
    @planner.room = @room
    authorize @planner
    respond_to do |format|
      if @planner.save
        @planners = current_user.planners.where(room: @room)
        html = render_to_string(partial: "planner_card", formats: :html, locals: { planner: @planner })
        colorhtml = render_to_string(partial: "colorswatch", formats: :html, locals: { planner: @planners })
        # create the colorbar as a string using a partial
        format.html { redirect_to room_planners_path(@room) }
        format.json { render json: { html: html, colorswatch: colorhtml, price: @room.planner_items.sum { |item| item.price } } }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: { errors: @planner.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @planner = Planner.find(params[:id])
    authorize @planner
    @room = @planner.room
    @planner.destroy
    respond_to do |format|
    if @planner.destroy
      @planners = current_user.planners.where(room: @room)
      colorhtml = render_to_string(partial: "colorswatch", formats: :html, locals: { planner: @planners })
      # format.html {redirect_to room_planners_path(@room), status: :see_other}
      format.json { render json: {colorswatch: colorhtml, price: @room.planner_items.sum { |item| item.price } } }
    end
  end
  end

  private

  def planner_params
    params.require(:planner).permit(:frnshr_room_id, :frnshr_item_id)
  end

end

app/helpers/planners_helper.rb
module PlannersHelper
  def hue_from_hex(hex)
    color = Color::RGB.by_hex(hex)
    hsl_color = color.to_hsl
    hue = hsl_color.h * 360 # Convert hue from [0, 1] range to [0, 360] degrees
    hue.round(2)
  end

  def saturation_from_hex(hex)
    color = Color::RGB.by_hex(hex)
    hsl_color = color.to_hsl
    saturation = hsl_color.s
    saturation.round(2)
  end

  def value_from_hex(hex)
    color = Color::RGB.by_hex(hex)
    hsl_color = color.to_hsl
    value = hsl_color.l
    value.round(2)
  end
end

app/views/planners/_colorswatch.html.erb
<div id ="colorarea" data-refreshless-target="colorswatch">
  <%# <div style = "width: 450></div> %>
  <%total_item_no = @planners.count%>
  <% if @planners.count.positive?%>
    <%colored_items = @room.area_by_colors%>
    <% sorted_colored_items = colored_items.sort_by do |key, _| %>
      <% value = value_from_hex(key) %>
      <% if value == 0 %>
        <% [-1, hue_from_hex(key)] %>
      <% elsif value == 1 %>
        <% [2, hue_from_hex(key)] %>
      <% else %>
        <% [1, value, saturation_from_hex(key), hue_from_hex(key)] %>
      <% end %>
    <% end %>
    <% sorted_colored_items.each do |key, value|%>
      <div style="background-color: <%= key %>; width: <%= value.to_f/@room.total_area*100 %>%;">
        <%# <%=key%>
        <%# <%=value%>
        <%# <%=value.to_f/total_item_no*100%>
      </div>
    <%end%>
  <%else%>
    <p>Add some items from your favorites!</p>
  <%end%>
</div>

app/views/planners/_planner_card.html.erb
<%# class="d-flex col-lg-4 col-md-6 col-sm-12 mb-3" %>
<div data-refreshless-target="plannercard">
  <div class="planner-card">
    <div class="planner-image" style="background-image: url('<%= planner.item.photo %>')">
    </div>
    <div class="planner-card-infos">
      <%# <p><%= planner.item.name </p> %>
      <p><a class="shop-link text-decoration-none text-info" href="<%= planner.item.shop_url %>" target="_blank"><span class="planner-item-name"><%= planner.item.name %></span><i class="fa-solid fa-up-right-from-square"></i></a></p>
      <p>¥ <%= number_with_delimiter(planner.item.price) %></p>
    </div>
    <div class="remove-item-from-planner ">
      <%= simple_form_for [@room, @planner],url: planner_path(planner), method: :delete , data: { refreshless_target: "removeitem", action: "submit->refreshless#remove"} do |f| %>
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
        <%= f.button :button do %>
          <i class="fa-solid fa-circle-minus"></i>
        <% end %>
      <%end%>
    </div>
  </div>
</div>

app/views/planners/_plannerspart.html.erb
<div class="planner">
  <%= render "shared/planner-bar" %>
  <div class="planner-title">
    <h4>Welcome to your Room Planner!</h4>
  </div>
  <div class="planner-card-container" data-refreshless-target="display">
    <%@planners.each do |planner|%>
      <%= render "planner_card", planner: planner%>
    <%end%>
  </div>
</div>

app/views/planners/_printing.html.erb
<div class="container">
  <h1 class="planner-heading">Room Planner - Shopping List Version</h1>
  <div class ="floating">
    <h2>Your color swatch:</h2>
    <%= render "colorswatch"%>
  </div>
  <h2>Your planned items:</h2>
  <div class = "row">
    <%total_price = 0%>
    <% shop_names = @planners.map { |planner| planner.item.shop_name }.uniq %>
    <% shop_names.each do |shop| %>
      <h3><%= shop %></h3>
      <table style="border: 0;">
        <tbody>
          <tr>
            <td style = "width:10%;"><strong>Color</strong></td>
            <td style = "width:35%;"><strong>Item</strong></td>
            <td><strong>Item Id</strong></td>
            <td><strong>Quantity</strong></td>
            <td><strong>Unit Price</strong></td>
            <td><strong>Link</strong></td>
          </tr>
          <% same_shop = @planners.select { |planner| planner.item.shop_name == shop } %>
          <% same_items = same_shop.map { |planner| planner.item.name }.tally %>
          <% same_items.each do |name, count| %>
            <% details = @planners.select{ |planner| planner.item.name == name} %>
            <% total_price += details.sum { |planner| planner.item.price }%>
            <tr>
              <td style="background-color: <%= details.first.item.color %>;"></td>
              <td><%= name %></td>
              <td><%= details.first.item.shop_item_id %></td>
              <td><%= count %></td>
              <td><%= details.first.item.price%></td>
              <td><%= link_to "url", details.first.item.shop_url, target: "_blank" %></td>
            </tr>
            <p></p>
          <% end %>
        </tbody>
      </table>
      <p></p>
    <% end %>
  </div>
  <div style="text-align: right;">
    <h2>Total Price : ¥<%= total_price %></h2>
  </div>
  <table style="border:none">
    <tbody style="border:none">
    <% unique_planners = @planners.uniq { |planner| planner.item.id } %>
      <% unique_planners.each_slice(4) do |slice| %>
        <tr style="border:none">
          <% slice.each do |planner|%>
            <td style="border:none; font-size:15px">
              <%= image_tag planner.item.photo, width:"100px", height:"100px" %>
              <%= planner.item.name %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/planners/_room_planners.html.erb
<div class="add-to-planner">
  <%= simple_form_for [@room, @planner], data: { refreshless_target: "form", action: "submit->refreshless#add"} do |f| %>
    <%= f.input :item_id , as: :hidden, input_html: {value: wishlist.item.id} %>
    <%= f.button :button do %>
      <i class="fa-solid fa-circle-plus"></i>
    <% end %>
  <% end %>
</div>

app/views/planners/index.html.erb
<% content_for :meta_title, "FRNSHR - Room Planner" %>
<div class="page-container" data-controller="refreshless">
  <div class="wishbar-container">
    <%= render "shared/wishbar-right", wishlists: @wishlists %>
  </div>
  <div class="planners-container">
    <%= render "plannerspart" %>
  </div>
</div>