config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :rooms, except: [:edit, :update] do
    resources :wishlists, only: [:index, :create]
    resources :planners, only: [:index, :create]
  end
  resources :wishlists, only: [:destroy]
  resources :planners, only: [:destroy]
end

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="curve">
    <svg width="100%" height="100%" id="svg" viewBox="0 0 1440 490" xmlns="http://www.w3.org/2000/svg" class="transition duration-300 ease-in-out delay-150"><path d="M 0,600 L 0,225 C 149.92857142857144,199.73214285714286 299.8571428571429,174.46428571428572 415,182 C 530.1428571428571,189.53571428571428 610.4999999999999,229.875 722,286 C 833.5000000000001,342.125 976.1428571428573,414.03571428571433 1101,444 C 1225.8571428571427,473.96428571428567 1332.9285714285713,461.98214285714283 1440,450 L 1440,600 L 0,600 Z" stroke="none" stroke-width="0" fill="#d5bdaf" fill-opacity="1" class="transition-all duration-300 ease-in-out delay-150 path-0" transform="rotate(-180 720 300)"></path></svg>
    <div class="image-container">
      <%= image_tag("landing-room.png", class: "landing-image") %>
    </div>
    <div class="slogan-container">
      <div class="slogan"><span>From Vision to Reality:</span><span> Your Ideal Furniture Awaits</span></div>
      <div class="call-to-action">
        <div class="cool-button-container">
          <a href="/rooms/new" class="button type--A">
            <div class="button__line"></div>
            <div class="button__line"></div>
            <span class="button__text">Get Inspired</span>
            <div class="button__drow1"></div>
            <div class="button__drow2"></div>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%# <a target="_blank" href="https://github.com/rubykytam"><i class="fab fa-github"></i></a> %>
    <%# <a target="_blank" href="https://github.com/Nikita-Nagras"><i class="fab fa-github"></i></a>
    <a target="_blank" href="https://github.com/ntw3001"><i class="fab fa-github"></i></a>
    <a target="_blank" href="https://github.com/Jasufr"><i class="fab fa-github"></i></a> %>
    <a target="_blank" href="https://github.com/Jasufr/FRNSHR"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    <a href="#">Privacy</a>・
    <a href="#">Terms</a>・
    <span>2024 FRNSHR,Inc.</span>
  </div>
</div>

app/views/shared/_loading-search-page.html.erb
<div class="loader-container">
  <div class="loader">
    <div class="loader-title">
      <h1>Seeking Your Decor Treasures</h1>
      <div>
        <div class="spinner-grow first-spinner" style="width: 1rem; height: 1rem;" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
        <div class="spinner-grow second-spinner" style="width: 1rem; height: 1rem;" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
        <div class="spinner-grow third-spinner" style="width: 1rem; height: 1rem;" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>
    </div>
    <div class="getting-items-loadings">
      <div class="loading-messages-slider">
        <p>Searching for Items...</p>
        <p>Importing Items...</p>
        <p>...And doing some other cool stuff</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_narrow-search-current.html.erb
<div class="searchbar">
  <%= form_with url: room_wishlists_path(@room), method: :get do |f| %>
    <div class="narrow-search">
      <div class="palette-container d-flex">
        <% @room.palette.each do |color| %>
          <div class="room-color" style="background-color: <%= color %>"></div>
        <% end %>
      </div>
      <div class="narrowbar">
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Room Type
          </button>
          <ul class="dropdown-menu room-type-menu">
            <%= f.collection_radio_buttons :room_type, Room::ROOMS.map {|room| [room, room.capitalize]}, :first, :last, {checked: params[:room_type]}, {class: "d-none"} %>
          </ul>
        </div>
        <%# searchbar entry %>
        <%= f.text_field :query,
          class: "form-control search-input",
          placeholder: "What are you looking for?"
      %>
        <%# price range entry %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Price</button>
          <ul class="dropdown-menu price-range-menu">
            <%= f.collection_radio_buttons :price_range, [["0-2000"], ["2000-5000"], ["5000-10000"], ["10000-20000"], ["20000-30000"], ["30000-40000"],], :first, :last, {checked: params[:price_range]}, {class: "d-none"} %>
          </ul>
        </div>
        <%# furniture size entry %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dimensions
          </button>
          <ul class="dropdown-menu dimensions-menu">
            <label for="width" class="form-label">Width</label>
            <output id="rangevaluewidth">0</output>
            <%= f.range_field :width, :step => 10, :in => -1..300, value: params[:width] || -1, oninput: "rangevaluewidth.value=(parseInt(value, 10)+ 1)" %>
            <label for="height" class="form-label">Height</label>
            <output id="rangevalueheight">0</output>
            <%= f.range_field :height, :step => 10, :in => -1..300, value: params[:height] || -1, oninput: "rangevalueheight.value=(parseInt(value, 10)+ 1)" %>
            <label for="depth" class="form-label">Depth</label>
            <output id="rangevaluedepth">0</output>
            <%= f.range_field :depth, :step => 10, :in => -1..300, value: params[:depth] || -1, oninput: "rangevaluedepth.value=(parseInt(value, 10)+ 1)" %>
          </ul>
        </div>
        <%# submit %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary search-button" %>
      </div>
      <%# reset search %>
      <a href="/rooms/<%= @room.id %>/wishlists" class="reset-button btn btn-danger">Reset</a>
    </div>
  <% end %>
</div>

app/views/shared/_narrow-search-old.html.erb
<div class="searchbar">
  <%= form_with url: room_wishlists_path(@room), method: :get do |f| %>
    <div class="narrow-search">
      <div class="palette-container d-flex">
        <% @room.palette.each do |color| %>
          <div class="room-color" style="background-color: <%= color %>"></div>
        <% end %>
      </div>
      <div class="narrowbar">
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Room Type
          </button>
          <ul class="dropdown-menu room-type-menu">
            <%= f.collection_radio_buttons :room_type, Room::ROOMS.map {|room| [room, room.capitalize]}, :first, :last, {checked: params[:room_type]}, {class: "d-none"} %>
          </ul>
        </div>
        <%# searchbar entry %>
        <%= f.text_field :query,
          class: "form-control search-input",
          placeholder: "What are you looking for?"
      %>
        <%# price range entry %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Price</button>
          <ul class="dropdown-menu price-range-menu">
            <%= f.collection_radio_buttons :price_range, [["0-2000"], ["2000-5000"], ["5000-10000"], ["10000-20000"], ["20000-30000"], ["30000-40000"],], :first, :last, {checked: params[:price_range]}, {class: "d-none"} %>
          </ul>
        </div>
        <%# furniture size entry %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dimensions
          </button>
          <ul class="dropdown-menu dimensions-menu">
            <label for="width" class="form-label">Width</label>
            <output id="rangevaluewidth">0</output>
            <%= f.range_field :width, :step => 10, :in => -1..300, value: params[:width] || -1, oninput: "rangevaluewidth.value=(parseInt(value, 10)+ 1)" %>
            <label for="height" class="form-label">Height</label>
            <output id="rangevalueheight">0</output>
            <%= f.range_field :height, :step => 10, :in => -1..300, value: params[:height] || -1, oninput: "rangevalueheight.value=(parseInt(value, 10)+ 1)" %>
            <label for="depth" class="form-label">Depth</label>
            <output id="rangevaluedepth">0</output>
            <%= f.range_field :depth, :step => 10, :in => -1..300, value: params[:depth] || -1, oninput: "rangevaluedepth.value=(parseInt(value, 10)+ 1)" %>
          </ul>
        </div>
        <%# submit %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary search-button" %>
      </div>
      <%# reset search %>
      <a href="/rooms/<%= @room.id %>/wishlists" class="reset-button btn btn-danger">Reset</a>
    </div>
  <% end %>
</div>

app/views/shared/_narrow-search.html.erb
<div class="searchbar">
  <%= form_with url: room_wishlists_path(@room), method: :get do |f| %>
    <div class="narrow-search">
      <div class="palette-container d-flex">
        <% @room.palette.each do |color| %>
          <input class="form-check-input check_boxes optional color-selector" type="checkbox" value="<%= color %>" name="colors[]" id="color-<%= color %>" <%= "checked" if params[:colors].present? && params[:colors].include?(color)%> >
          <label class="form-check-label collection_check_boxes" for="color-<%= color %>" style='background-color: <%= color %>'></label>
        <% end %>
      </div>
      <div class="narrowbar">
        <%# <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Room Type
          </button>
          <ul class="dropdown-menu room-type-menu">
            <%= f.collection_radio_buttons :room_type, Room::ROOMS.map {|room| [room, room.capitalize]}, :first, :last, {checked: params[:room_type]}, {class: "d-none"} %>
        <%# </ul> %>
        <%# </div> %>
        <div style="position:relative">
          <button type="button" class="btn btn-secondary"><i class="fa-solid fa-palette"></i></button>
          <input type="color" name="colors[]" value="#000001" style="opacity:0; position:absolute; left:0;top:0;width:100%"/>
          <%# <input type="text" id="colorpicker" data-coloris data-controller="colorpicker" name="colors[]" value="#000001"/> %>
        </div>
        <%# searchbar entry %>
        <%= f.text_field :query,
          class: "form-control search-input",
          placeholder: "Narrow your search..."
        %>
        <%# price range entry - REPLACE WITH SORT BY ASC/DESC %>
        <%# <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Price</button>
          <ul class="dropdown-menu price-range-menu">
            <%= f.collection_radio_buttons :price_range, [["0-2000"], ["2000-5000"], ["5000-10000"], ["10000-20000"], ["20000-30000"], ["30000-40000"],], :first, :last, {checked: params[:price_range]}, {class: "d-none"} %>
        <%# </ul>
        </div> %>
        <%# furniture size entry %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle height-100%" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dimensions
          </button>
          <ul class="dropdown-menu dimensions-menu">
            <label for="width" class="form-label">Width</label>
            <output id="rangevaluewidth">0</output>
            <%= f.range_field :width, :step => 10, :in => -1..300, value: params[:width] || -1, oninput: "rangevaluewidth.value=(parseInt(value, 10)+ 1)" %>
            <label for="height" class="form-label">Height</label>
            <output id="rangevalueheight">0</output>
            <%= f.range_field :height, :step => 10, :in => -1..300, value: params[:height] || -1, oninput: "rangevalueheight.value=(parseInt(value, 10)+ 1)" %>
            <label for="depth" class="form-label">Depth</label>
            <output id="rangevaluedepth">0</output>
            <%= f.range_field :depth, :step => 10, :in => -1..300, value: params[:depth] || -1, oninput: "rangevaluedepth.value=(parseInt(value, 10)+ 1)" %>
          </ul>
        </div>
        <%# submit %>
        <%= submit_tag "Search", name: "", class: "btn btn-success search-button" %>
      </div>
      <div class="d-flex ml-4px mr-4px">
        <div class="inline-text">Price</div>
        <div><%= link_to raw('<i class="fa-solid fa-angle-up"></i>'), {controller: "wishlists", action: "index", sort: "asc", height: params[:height], width: params[:width], depth: params[:depth], query: params[:query]}, method: :get, class: "btn btn-secondary" %></div>
        <div><%= link_to raw('<i class="fa-solid fa-angle-down"></i>'), {controller: "wishlists", action: "index", sort: "desc", height: params[:height], width: params[:width], depth: params[:depth], query: params[:query]}, method: :get, class: "btn btn-secondary" %></div>
      </div>
      <%= f.hidden_field :sort, type: :hidden, value: params[:sort] %>
      <%# reset search %>
      <a href="/rooms/<%= @room.id %>/wishlists" class="reset-button btn btn-outline-danger">Reset</a>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-light navbar-lewagon">
  <div class="container-fluid d-flex flex-nowrap">
    <div class="d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
        <h2 class="brand-title m-0 text-light">FRNSHR</h2>
      <% end %>
    </div>
    <div class="d-flex justify-content-end">
      <% if user_signed_in? %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <%= link_to "New Room",  "/rooms/new", class: "dropdown-item" %>
            </li>
            <li class="nav-item">
              <%= link_to "Saved Rooms", "/rooms", class: "dropdown-item" %>
            </li>
            <li class="nav-item">
              <%= link_to "Settings", "#", class: "dropdown-item" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </li>
          </ul>
        </div>
      <% else %>
        <div class="nav-item ms-3 text-decoration-none">
          <%= link_to "Login", new_user_session_path, class: "btn btn-light login-button px-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_planner-bar.html.erb
<div class="planner-bar">
  <div class="planner-bar-leftpart">
    <p class="palette-title ms-3">Room colors :</p>
    <div class="palette-container d-flex me-4">
      <% @room.palette.each do |color| %>
        <div class="room-color" style="background-color: <%= color %>"></div>
      <% end %>
    </div>
    <p class="palette-title">Color ratios :</p>
    <div class="automatic-palette-container"><%= render "planners/colorswatch" %></div>
    <%= render "shared/total_price" %>
  </div>
  <%= link_to "Share", room_planners_path(@room, format: :pdf), target: "_blank", class: "btn btn-primary rounded-3 text-white" %>
</div>

app/views/shared/_search-results.html.erb
<div class="search" data-controller="loadingpage" >
  <%= render "shared/narrow-search" %>
  <div class="search-results">
    <div id="items">
      <% if @items.any? %>
        <div class="results-container">
          <% @items.each do |item| %>
            <%= render item, room: @room %>
          <% end %>
        </div>
      <% else %>
        <div class="d-flex justify-content-center mt-5">
          <em>No items found.</em>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_status.html.erb
<div class="wishbar-header">
  <p class="wishbar-title">Favorites</p>
  <p class="wishlists-counter" ><span data-searchpage-target="counter"><%= wishlists.count %></span> items selected</p>
  <% if current_page?(room_planners_path) %>
    <%= link_to "Back to Search", room_wishlists_path, class: "btn btn-primary button-back-to-search", role: "button" %>
  <% end %>
  <% if current_page?(room_wishlists_path)%>
    <%= link_to "Visualize Decor", room_planners_path, class: "button-planner text-white btn btn-primary", role: "button" %>
  <% end %>
</div>

app/views/shared/_total_price.html.erb
<div  data-refreshless-target="totalprice">
  <% totalprice = 0 %>
  <% @planners.each do |planner| %>
    <% totalprice += planner.item.price.to_i %>
  <% end %>
  <p class="totalpricep ms-3"><span>Total :</span> ¥<span id="totalprice"><%= number_with_delimiter(totalprice) %></span> </p>
</div>

app/views/shared/_wishbar-right.html.erb
<div class="wishbar">
  <%= render "shared/status", wishlist: @wishlist, wishlists: @wishlists%>
  <div class="wishitems-container scrollbar"  id="style-4" data-searchpage-target="wishlistsubDisplay">
    <% if wishlists.any? %>
      <% wishlists.each do |wishlist| %>
        <%= render "shared/wishlistcard", wishlist: wishlist%>
      <% end %>
      <em class="empty-wishlist-text p-3" data-searchpage-target ="statement"></em>
    <% else %>
      <em class="empty-wishlist-text p-3" data-searchpage-target ="statement">Add some items to your wishlist...</em>
    <% end %>
  </div>
</div>

app/views/shared/_wishlistcard.html.erb
<div class="wishitem" data-searchpage-target="wishlistcard">
  <div class="wishitem-image" style="background-image: url('<%= wishlist.item.photo %>')"></div>
  <div class="wishitem-info">
    <% if current_page?(room_planners_path) %>
      <p><i class="fa-solid fa-ruler"></i> <%= wishlist.item.x_dimension %> x <%= wishlist.item.y_dimension %> x <%= wishlist.item.z_dimension %></p>
    <% end %>
    <%# <p><%= wishlist.item.name </p> %>
    <div class="wishitem-lastline">
      <p>¥ <%= number_with_delimiter(wishlist.item.price) %></p>
      <%# <p><a class="text-decoration-none" href="<%= wishlist.item.shop_url " target="_blank">Shop</a></p> %>
      <% if current_page?(room_planners_path) %>
        <%= render "room_planners", wishlist: wishlist %>
        <%# <% else %>
      <% end %>
      <%= button_to wishlist_path(wishlist, origin: params[:controller]), method: :delete, data: {turbo_method: :delete}, class: "remove-button" do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </div>
  </div>
</div>