config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :rooms, except: [:edit, :update] do
    resources :wishlists, only: [:index, :create]
    resources :planners, only: [:index, :create]
  end
  resources :wishlists, only: [:destroy]
  resources :planners, only: [:destroy]
end

app/models/room.rb
class Room < ApplicationRecord
  self.table_name = "frnshr_rooms"
  belongs_to :user, foreign_key: "frnshr_user_id"
  has_many :wishlists, foreign_key: "frnshr_room_id", dependent: :destroy
  has_many :planners, foreign_key: "frnshr_room_id", dependent: :destroy
  has_many :planner_items, foreign_key: "frnshr_room_id", through: :planners, source: :item
  has_many :wish_items, foreign_key: "frnshr_room_id", through: :wishlists, source: :item

  validates :room_type, presence: true
  validates :palette, presence: true
  ROOMS = ['kitchen', 'bathroom', 'bedroom', 'living', 'dining', 'garden', 'kids']
  validates :room_type, inclusion: { in: ROOMS }

  def total_area
    planner_items.sum { |item| item.surface_area   }
  end


  def area_by_colors
    planners.joins(:item).group('planners.id', 'items.color').each_with_object({}) do |planner, result|
      color = planner.item.color
      surface_area = planner.item.surface_area
      result[color] ||= 0
      result[color] += surface_area
    end
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = policy_scope(Room)
  end

  def show
    @room = Room.find(params[:id])
    authorize @room
  end

  def new
    @room = Room.new
    authorize @room
  end

  def create
    @room = Room.new(room_params)
    @room.user = current_user
    authorize @room
    if @room.save
      redirect_to room_wishlists_path(@room, searching: true)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @room = Room.find(params[:id])
    authorize @room
    @room.destroy
    redirect_to rooms_path, status: :see_other
  end

  private

  def room_params
    params.require(:room).permit(:room_type, palette: [])
  end
end

app/views/rooms/index.html.erb
<% content_for :meta_title, "FRNSHR - Your saved rooms" %>
<div class="container">
  <h2 class="rooms-index-title">Your saved rooms with color planner: </h2>
  <div class = "rooms-container">
    <% @rooms.each do |room|%>
      <%# <div class="d-flex col-lg-6 col-md-6 col-sm-12 mb-8"> %>
      <div class = "saved_room_cards">
        <%= link_to room_planners_path(room), class: "room-card-link" do  %>
          <% @planners = room.planners %>
          <% @room = room %>
          <div class="room-swatch-container"><%= render "planners/colorswatch", room: room %></div>
          <div class = "room-card-infos">
            <p class="mb-0 me-4"><%= room.room_type.capitalize %> :</p>
            <div class="d-flex"><% @room.palette.each do |color| %>
                <div class="room-color" style="background-color: <%= color %>"></div>
              <% end %></div>
          </div>
        <% end %>
        <%= button_to room_path(room), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "remove-button" do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </div>
      <%# </div> %>
    <%end%>
  </div>
</div>

app/views/rooms/new.html.erb
<% content_for :meta_title, "FRNSHR - Room composer" %>
<div class="container">
  <div class="form-container new-room-form-container">
    <div class = "favoritecolor-card">
      <h2>Define Your Decor</h2>
      <%= simple_form_for(@room, html: { data: { controller: 'colorscheme' } }) do |f| %>
        <%= f.hidden_field :room_type, data: { colorscheme_target: 'room' } %>
        <div class="room-card-container">
          <% Room::ROOMS[0..-2].each do |room| %>
            <button data-action="click->colorscheme#roomchecking" data-roomtype="<%= room %>" class="room-card"
              style="background-image: url('<%= image_path("#{room}.jpg") %>'); ">
              <!-- Your button text or content -->
              <%= room.capitalize %>
            </button>
          <% end %>
        </div>
        <p>Main Tone Choice:</p>
        <input name="colorselect" type="color" data-colorscheme-target="usercolor" data-action="input->colorscheme#suggestion" class="favoritecolor" value="#FFFFFF">
        <div class = "schemetitle" data-colorscheme-target = "title"></div>
        <div class = "scheme-card-container" data-colorscheme-target = "displayArea">
        </div>
        <p class="design-your-room-btn"><%= f.button :submit, "Search Decor Options", class: "btn btn-primary text-white" %></p>
      </div>
    <% end %>
  </div>
</div>